inspect:
- app:
    name: ShiftLeftJS
    additional-findings:
    - hsl-secrets
    policy: io.shiftleft/default
    language: JAVASCRIPT
additional-findings:
  hsl-secrets:
    entropy: 0.5
    name: secrets
